### Tüm görevleri getir
GET http://localhost:3000/tasks


### Görev getir
GET http://localhost:3000/tasks/4


### Yeni görev oluştur
POST http://localhost:3000/tasks
Content-Type: application/json

{
    "title": "Post ile Görev oluştur",
    "desc": "ilk görevi oluştur",
    "priority": "Önemli",
    "assignee": "Unknown",
    "completed": false
}


### PUT Task güncelle 
PUT http://localhost:3000/tasks/6
Content-Type: application/json

{
    "title": "Görev Gücellendi",
    "desc": "Bu task TEKRAR güncellendi.",
     "priority": "Orta",
    "assignee": "Mert Ünal",
    "completed": true
}


### Delete Task
DELETE  http://localhost:3000/tasks/3